# Set the file name and size for the command history
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

# now, simply add these two lines in your ~/.zshrc

# source antidote
source /usr/share/zsh-antidote/antidote.zsh

# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load

# Set the file name for the completion settings generated by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

# Load and initialize the completion system
autoload -Uz compinit
compinit

# Source the plugins for syntax highlighting and autosuggestions
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

#plugins
plugins=(git bundler dotenv osx zsh-syntax-highlighting zsh-autosuggestions)

# Initialize the starship prompt
eval "$(starship init zsh)"

# Define some aliases for convenience
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias upgrade='sudo pacman -Syyu'
alias mirror='sudo reflector --latest 6 --sort rate --save /etc/pacman.d/mirrorlist'
