# .zshrc
# Lazy-load antidote and generate the static load file only when needed
zsh_plugins=${ZDOTDIR:-$HOME}/.zsh_plugins
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  (
    source /usr/share/zsh-antidote/antidote.zsh
    antidote bundle <${zsh_plugins}.txt >${zsh_plugins}.zsh
  )
fi
source ${zsh_plugins}.zsh

# Set the file name and size for the command history
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

# Set the file name for the completion settings generated by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

# Load and initialize the completion system
autoload -Uz compinit
compinit

# Source the plugins for syntax highlighting and autosuggestions
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

#plugins
plugins=(git bundler dotenv osx zsh-syntax-highlighting zsh-autosuggestions)

# Initialize the starship prompt
eval "$(starship init zsh)"

# Define some aliases for convenience
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias upgrade='sudo pacman -Syyu'
alias mirror='sudo reflector --latest 6 --sort rate --save /etc/pacman.d/mirrorlist'
