#!/bin/sh

iDIR="$HOME/.config/waybar/icons"

get_backlight() {
    brightnessctl -m | grep -o '[0-9]\+%' | head -c-2
}

get_icon() {
    current=$(brightnessctl g)
    if   [ "$current" -lt 51  ]; then echo "$iDIR/brightness-20.png"
    elif [ "$current" -lt 102 ]; then echo "$iDIR/brightness-40.png"
    elif [ "$current" -lt 153 ]; then echo "$iDIR/brightness-60.png"
    elif [ "$current" -lt 204 ]; then echo "$iDIR/brightness-80.png"
    elif [ "$current" -lt 255 ]; then echo "$iDIR/brightness-90.png"
    else echo "$iDIR/brightness-100.png"
    fi
}

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                -i "$(get_icon)" "Brightness : $(get_backlight)%"
}

change_backlight() {
    brightnessctl set "$1" && notify_user
}

case "$1" in
    --get) brightnessctl g ;;
    --inc) change_backlight "+10%" ;;
    --dec) change_backlight "10%-" ;;
    *)     get_backlight ;;
esac
