#!/bin/sh

ICON_DIR="$HOME/.config/waybar/icons"

get_volume() {
    pamixer --get-volume
}

get_icon() {
    local volume=$(get_volume)
    if [ "$volume" -eq 0 ]; then
        echo "$ICON_DIR/volume-mute.png"
    elif [ "$volume" -le 30 ]; then
        echo "$ICON_DIR/volume-low.png"
    elif [ "$volume" -le 60 ]; then
        echo "$ICON_DIR/volume-mid.png"
    else
        echo "$ICON_DIR/volume-high.png"
    fi
}

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume: $(get_volume)%"
}

adjust_volume() {
    pamixer $1 $2 && notify_user
}

toggle_mute() {
    local state=$(pamixer --get-mute)
    local icon="$ICON_DIR/volume-mute.png"
    local message="Volume Switched OFF"
    
    if [ "$state" = "true" ]; then
        pamixer -u
        icon="$(get_icon)"
        message="Volume Switched ON"
    else
        pamixer -m
    fi
    
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "$message"
}

toggle_mic() {
    local state=$(pamixer --default-source --get-mute)
    local icon="$ICON_DIR/microphone-mute.png"
    local message="Microphone Switched OFF"
    
    if [ "$state" = "true" ]; then
        pamixer --default-source -u
        icon="$ICON_DIR/microphone.png"
        message="Microphone Switched ON"
    else
        pamixer --default-source -m
    fi
    
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "$message"
}

notify_mic_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$ICON_DIR/microphone.png" "Mic-Level: $(pamixer --default-source --get-volume)%"
}

case "$1" in
    --get) get_volume ;;
    --inc) adjust_volume -i 5 ;;
    --dec) adjust_volume -d 5 ;;
    --toggle) toggle_mute ;;
    --toggle-mic) toggle_mic ;;
    --get-icon) get_icon ;;
    --get-mic-icon) echo "$ICON_DIR/microphone.png" ;;
    --mic-inc) pamixer --default-source -i 5 && notify_mic_user ;;
    --mic-dec) pamixer --default-source -d 5 && notify_mic_user ;;
    *) get_volume ;;
esac
