#!/bin/sh

iDIR="$HOME/.config/waybar/icons"

get_volume() {
    pamixer --get-volume
}

get_icon() {
    vol=$(get_volume)
    if   [ "$vol" -eq 0  ]; then echo "$iDIR/volume-mute.png"
    elif [ "$vol" -le 30 ]; then echo "$iDIR/volume-low.png"
    elif [ "$vol" -le 60 ]; then echo "$iDIR/volume-mid.png"
    else echo "$iDIR/volume-high.png"
    fi
}

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                -i "$(get_icon)" "Volume : $(get_volume) %"
}

change_volume() {
    pamixer $1 && notify_user
}

toggle_mute() {
    if pamixer --get-mute; then
        pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                                  -i "$(get_icon)" "Volume Switched ON"
    else
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                                  -i "$iDIR/volume-mute.png" "Volume Switched OFF"
    fi
}

toggle_mic() {
    if pamixer --default-source --get-mute; then
        pamixer --default-source -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                                                   -i "$iDIR/microphone.png" "Microphone Switched ON"
    else
        pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                                                   -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
    fi
}

get_mic_icon() {
    echo "$iDIR/microphone.png"
}

notify_mic_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low \
                -i "$(get_mic_icon)" "Mic-Level : $(pamixer --default-source --get-volume) %"
}

change_mic_volume() {
    pamixer --default-source $1 && notify_mic_user
}

case "$1" in
    --get)        get_volume ;;
    --inc)        change_volume "-i 5" ;;
    --dec)        change_volume "-d 5" ;;
    --toggle)     toggle_mute ;;
    --toggle-mic) toggle_mic ;;
    --get-icon)   get_icon ;;
    --get-mic-icon) get_mic_icon ;;
    --mic-inc)    change_mic_volume "-i 5" ;;
    --mic-dec)    change_mic_volume "-d 5" ;;
    *)            get_volume ;;
esac
